apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.12.0
  count: 1
  elasticsearchRef:
    name: quickstart  # 保留此引用，用于自动连接 Elasticsearch 集群
    namespace: pema-elastic-system